spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      auto-index-creation: true
  redis:
    host: ${REDIS_HOST}
    port: 18860
    username: default
    password: ${REDIS_PASSWORD}
    ssl: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: nomeshdadhich9057@gmail.com
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal-app

WeatherStack:
  api:
    key: ${WEATHERSTACK_API_KEY}