spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal-app