spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=journaldb
spring.data.mongodb.username=${MONGODB_USERNAME}
spring.data.mongodb.password=${MONGODB_PASSWORD}
spring.data.mongodb.auto-index-creation=true